title: "Portfolio de Tom Latchimy"
description: "Portfolio professionnel en cybersécurité – projets, analyses et apprentissages."

remote_theme: cotes2020/jekyll-theme-chirpy

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives
