title: "Portfolio de Tom Latchimy"
description: "Portfolio professionnel en cybersécurité – projets, analyses et apprentissages."
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme

layout: default



